[package]
name = "svg-radar-chart"
version = "1.0.11"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
core = { path = "../core" }
wasm-bindgen = "0.2.78"
serde_json = "1.0.74"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
